ORG &8000
	DI 			; DESABILITA AS INTERRUPCOES
		LD A,&C3	; CODIGO PARA INSTRUCAO JP
		LD (&0038),A	; CARREGA O CODIGO DA INSTRUCAO JP
				; PARA O ENDERECO DE MEMORIA DA 
				; INTERRUPCAO 
		LD HL,INTHNDL	; CODIGO QUE TRATARA A INTERRUPCAO
		LD (&0039), HL	; CARREGA O CODIGO QUE TRATARA A 
				; INTERRUPCAO NO PROXIMO ENREDECO 
				; DE MEMORIA
	EI 

LOOP:
	HALT
JR LOOP
		
INTHNDL:
	EXX			; TROCA HL,BC E DE COM HL',BC' E DE'
	EX AF,AF'		; TROCA A E F COM A' E F'
	LD HL,RASTERCOLORS :IH_RASTERCOLORS_PLUS2
	LD B,&F5 		; TODOS OS ENDERECOS DE MEMORIA QUE 
				; COMECAM COM &F5 REFENCIAM A SAIDA
				; DE VIDEO
	IN A,(C)		; NA VERDADE SIGNIFICA IN A,(BC)
	RRA			
	JP NC,INTHNDLOK
	LD HL,RASTERCOLORS
INTHNDLOK:
	LD BC, &7F00		; GATEWAY GRAFICO
	OUT (C),C		; NA VERDADE SIGNIFICA OUT (BC),C
	LD A,(HL)
	OUT (C),A		; CARREGA O ARRAY DE CORES NO GATEWAY 
				; GRAFICO
	INC HL
	LD (IH_RASTERCOLORS_PLUS2-2), HL
	EX AF, AF'
	EXX
	EI

RASTERCOLORS:
	DB &4C,&43,&52,&5C,&5E,&5F ; HARDWARE COLOR